name: Tree-sitter

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    generate:
        name: Generate and Test
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - run: npm ci
            - run: npm run generate
            - run: npm run test

    bindings-rust:
        name: Build Rust bindings
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - uses: actions/checkout@v3

            - name: Install Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable

            - name: Cache cargo dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry/index
                      ~/.cargo/registry/cache
                      ~/.cargo/git/db
                  key: cargo-deps-${{ hashFiles('**/Cargo.lock') }}

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build

    bindings-node:
        name: Build Node bindings
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
            fail-fast: true

        continue-on-error: true
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: node-gyp configure
              run: npm run configure

            - name: node-gyp build
              run: npm run build
