name: Tree-sitter

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

jobs:
    generate:
        name: Generate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - run: npm ci
            - run: npm run generate

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - run: npm ci
            - run: npm run test
